// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX89LDbBfwI601g4E8jrw-5jkfBP9wpR4',
    appId: '1:333508306032:web:afb14f4cdb834981cc80b5',
    messagingSenderId: '333508306032',
    projectId: 'gestiondesarrolladores',
    authDomain: 'gestiondesarrolladores.firebaseapp.com',
    storageBucket: 'gestiondesarrolladores.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM3IDykPNxgExlxjsxpmqu4OisL1pt5WE',
    appId: '1:333508306032:android:e6280f735f6f65c5cc80b5',
    messagingSenderId: '333508306032',
    projectId: 'gestiondesarrolladores',
    storageBucket: 'gestiondesarrolladores.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ9Z5Bjzkt9Zs5kRhuAyfMxud3rqmz1jk',
    appId: '1:333508306032:ios:f35bc951ef7e0fb8cc80b5',
    messagingSenderId: '333508306032',
    projectId: 'gestiondesarrolladores',
    storageBucket: 'gestiondesarrolladores.firebasestorage.app',
    iosBundleId: 'com.example.gestionEquipos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ9Z5Bjzkt9Zs5kRhuAyfMxud3rqmz1jk',
    appId: '1:333508306032:ios:f35bc951ef7e0fb8cc80b5',
    messagingSenderId: '333508306032',
    projectId: 'gestiondesarrolladores',
    storageBucket: 'gestiondesarrolladores.firebasestorage.app',
    iosBundleId: 'com.example.gestionEquipos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX89LDbBfwI601g4E8jrw-5jkfBP9wpR4',
    appId: '1:333508306032:web:132e8e8ff20dba1ecc80b5',
    messagingSenderId: '333508306032',
    projectId: 'gestiondesarrolladores',
    authDomain: 'gestiondesarrolladores.firebaseapp.com',
    storageBucket: 'gestiondesarrolladores.firebasestorage.app',
  );

}